apiVersion: v1 
kind: Pod 
metadata: 
  creationTimestamp: null 
  labels: 
    run: secret-xfusion 
  name: secret-xfusion 
spec: 
  containers: 
  - image: ubuntu:latest 
    name: secret-container-xfusion 
    command: ["sleep", "2000"] 
    volumeMounts: 
      - name: secret-volume 
        mountPath: "/opt/cluster" 
  volumes: 
    - name: secret-volume 
      secret: 
        secretName: news