apiVersion: apps/v1 
kind: Deployment 
metadata: 
  labels: 
    app: httpd-deploy 
  name: httpd-deploy 
  namespace: devops 
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: httpd-deploy 
  strategy: 
    type: RollingUpdate 
    rollingUpdate: 
      maxUnavailable: 2 
      maxSurge: 1 
  template: 
    metadata: 
      labels: 
        app: httpd-deploy 
    spec: 
      containers: 
      - image: httpd:2.4.28 
        name: httpd