apiVersion: v1 
kind: Pod 
metadata: 
  name: time-check 
  namespace: xfusion 
spec: 
  containers: 
    - name: time-check 
      image: busybox:latest 
      command: 
        - "sh" 
        - "-c" 
        - "while true; do date; sleep $TIME_FREQ;done >> /opt/sysops/time/time-check.log" 
      env: 
        - name: TIME_FREQ 
          valueFrom: 
            configMapKeyRef: 
              name: time-config 
              key: TIME_FREQ 
      volumeMounts: 
      - mountPath: /opt/sysops/time 
        name: log-volume 
  volumes: 
  - name: log-volume 
    emptyDir: 
      sizeLimit: 100Mi 