apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: pv-datacenter 
spec: 
  capacity: 
    storage: 4Gi 
  volumeMode: Filesystem 
  accessModes: 
    - ReadWriteOnce 
  storageClassName: manual 
  hostPath: 
    path: /mnt/dba