apiVersion: apps/v1 
kind: Deployment 
metadata: 
  labels: 
    app: ic-devops 
  name: ic-deploy-devops 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: ic-devops 
  strategy: {} 
  template: 
    metadata: 
      labels: 
        app: ic-devops 
    spec: 
      initContainers: 
      - image: ubuntu:latest 
        name: ic-msg-devops 
        command: ['/bin/bash', '-c', 'echo Init Done - Welcome to xFusionCorp Industries > /ic/media'] 
        volumeMounts: 
        - mountPath: /ic 
          name: ic-volume-devops  
      containers: 
      - image: ubuntu:latest 
        name: ic-main-devops 
        command: ['/bin/bash', '-c', 'while true; do cat /ic/media; sleep 5; done'] 
        volumeMounts: 
        - mountPath: /ic 
          name: ic-volume-devops 
      volumes: 
      - name: ic-volume-devops 
        emptyDir: 
          sizeLimit: 100Mi