apiVersion: v1 
kind: Pod 
metadata: 
  creationTimestamp: null 
  labels: 
    app: nginx_app 
  name: pod-nginx 
spec: 
  containers: 
  - image: nginx:latest 
    name: nginx-container 
    resources: {} 
  dnsPolicy: ClusterFirst 
  restartPolicy: Always 
status: {} 