apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: drupal-mysql-pv 
spec: 
  capacity: 
    storage: 5Gi 
  volumeMode: Filesystem 
  accessModes: 
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Recycle 
  storageClassName: slow 
  hostPath: 
    path: /drupal-mysql-data 
--- 
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: drupal-mysql-pvc 
spec: 
  accessModes: 
    - ReadWriteOnce 
  volumeMode: Filesystem 
  resources: 
    requests: 
      storage: 3Gi 
  storageClassName: slow 
--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: drupal-mysql 
  labels: 
    app: drupal-mysql 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: drupal-mysql 
  template: 
    metadata: 
      name: drupal-mysql 
      labels: 
        app: drupal-mysql 
    spec: 
      containers: 
        - name: myslq-drupal-container 
          image: mysql:5.7 
          env: 
          - name: MYSQL_DATABASE 
            value: "drupal_databse" 
          - name: MYSQL_ROOT_PASSWORD 
            value: "R00t" 
          - name: MYSQL_PASSWORD 
            value: "MysqlPassword123@" 
          - name: MYSQL_USER  
            value: admin    
          volumeMounts: 
            - mountPath: /var/lib/mysql 
              name: drupal-mysql-pvc-volume 
      volumes: 
        - name: drupal-mysql-pvc-volume 
          persistentVolumeClaim: 
            claimName: drupal-mysql-pvc 
--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: drupal 
  labels: 
    app: drupal 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: drupal 
  template: 
    metadata: 
      name: drupal 
      labels: 
        app: drupal 
    spec: 
      containers: 
        - name: drupal-container 
          image: drupal:8.6 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: drupal-service 
spec: 
  selector: 
    app: drupal 
  ports: 
    - protocol: TCP 
      port: 80 
      targetPort: 80 
      nodePort: 30095 
  type: NodePort 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: drupal-mysql-service 
spec: 
  selector: 
    app: drupal-mysql 
  ports: 
    - protocol: TCP 
      port: 3306 
      targetPort: 3306 
  type: ClusterIP 